services:
  - type: web
    name: portal-academico
    env: dotnet
    plan: free
    buildCommand: dotnet publish -c Release -o out
    startCommand: cd out && dotnet "examen parcial.dll"
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000